### ISSUE TITLE
SortablejsModule Error

### ISSUE THREAD

**Issue by ArtisanDuCode** [SortableJS/angular-sortablejs#38]
I followed your Readme step by step. I have the following error when I import it into app.module.ts

`Error: TypeError: ctorParameters.map is not a function
	    at ReflectionCapabilities.parameters (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:2118:51)
	    at Reflector.parameters (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:2319:52)
	    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14336:81)
	    at CompileMetadataResolver.getTypeMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14301:28)
	    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14074:30)
	    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14143:51)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14136:46)
	    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14124:52)
	    at Array.forEach (native)
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js`

**Comment by smnbbrv** [comment]
Hi @ArtisanDuCode 

please tell more about your environment and angular version.

**Comment by ArtisanDuCode** [comment]
ASP .Net Core and Angular 1.6.4

**Comment by smnbbrv** [comment]
Just googled this and it does not seem our issue. Check https://stackoverflow.com/questions/41285889/ctorparameters-map-is-not-a-function-in-angular2-mdl
